base_url = "https://zahidkizmaz.github.io"

minify_html = true
compile_sass = true
generate_feed = true
build_search_index = true

theme = "tabi"
title = "Zahid Kizmaz"
default_language = "en"

[markdown]
render_emoji = true
highlight_code = true
highlight_theme = "css"
external_links_target_blank = true

[extra]
favicon_emoji = "🏂"
copy_button = false
custom_subset = true
default_theme = "dark"
feed_icon = true
footnote_backlinks = false
katex = false
quick_navigation_buttons = true
show_reading_time = false
skin = "teal"
theme_switcher = false
full_content_in_feed = true

menu = [
  { name = "blog", url = "blog", trailing_slash = true },
  { name = "about", url = "about", trailing_slash = true },
]

footer_menu = [
  { name = "blog", url = "blog", trailing_slash = true },
  { name = "about", url = "about", trailing_slash = true },
]

socials = [
  { name = "github", url = "https://github.com/zahidkizmaz/", icon = "github" },
  { name = "linkedin", url = "https://linkedin.com/in/zahidkizmaz", icon = "linkedin" },
]
