---
services:
    zola:
        build:
            context: .
            target: zola
        command: serve --interface 0.0.0.0 --base-url localhost --port 1111
        volumes:
            - .:/blog
        ports:
            - '1111:1111'
