---
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install pre-commit
        run: pipx install pre-commit

      - name: set PY env variable for pre-commit cache
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{env.PY}}|${{hashFiles('.pre-commit-config.yaml')}}

      - name: run linters via pre-commit
        run: pre-commit run --all --show-diff-on-failure --color=always
